language: php
php:
  - '7.1'
install:
  - composer install

before_install: true

before_script: true

script:
  - mkdir -p build/logs
  - php bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v