language: php
php:
  - '7.1'

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer install

before_script:
  - mkdir -p build/logs

script:
  - php bin/phpunit

after_success:
  - php vendor/bin/php-coveralls -v