directories:
  documents: "/../../var/uploads/"
  cache_upload_pdf: "../../../../../var/cache/pdf/"

supported_formats:
  -
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    type: "DOCX"
  -
    mime: "application/msword"
    type: "DOC"
  -
    mime: "application/pdf"
    type: "PDF"
  -
    mime: "text/html"
    type: "HTML"


bin_location:
  pdftohtml_bin: "/usr/local/bin/pdftohtml"
  pdfinfo_bin: "/usr/local/bin/pdfinfo"
